#!/usr/bin/env python3
"""
RQ Talent — Gulf oil & gas / shutdown job scraper.

Runs hourly via GitHub Actions. Pulls postings from official aggregator APIs
(Jooble, Careerjet) and open ATS APIs (Greenhouse, Lever), normalizes them to a
single schema, tags shutdown/turnaround roles, dedupes, and writes ../jobs.json.

Design notes
------------
* Stdlib only (urllib, json, re, hashlib) — nothing to break in CI.
* Every source is wrapped in try/except. One source failing never aborts the run.
* Results are MERGED with the existing jobs.json, so a blocked/empty run never
  wipes the feed. Entries unseen for `retention_days` are dropped.
* Datacenter IPs (incl. GitHub runners) get blocked by HTML job boards, so we
  rely on JSON APIs that are ToS-friendly and don't block. HTML/RSS adapters are
  included as optional best-effort only.

Secrets (set as GitHub repo secrets, read from env):
    JOOBLE_API_KEY     — free key from https://jooble.org/api/about
    CAREERJET_AFFID    — free affiliate id from https://www.careerjet.com/partners/
"""

import json, os, re, sys, time, hashlib, urllib.request, urllib.parse, urllib.error
from datetime import datetime, timezone, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(HERE, "config.json")
OUTPUT_PATH = os.path.normpath(os.path.join(HERE, "..", "jobs.json"))
OUTPUT_JS_PATH = os.path.normpath(os.path.join(HERE, "..", "jobs.js"))


def write_outputs(payload):
    """Write jobs.json (for fetch on GitHub Pages) AND jobs.js (a <script> that
    sets window.RQ_JOBS — works when the portal is opened locally via file://,
    where fetch() is blocked by the browser)."""
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    with open(OUTPUT_JS_PATH, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scraper/scrape.py. Do not edit by hand. */\n")
        f.write("window.RQ_JOBS = ")
        json.dump(payload, f, ensure_ascii=False)
        f.write(";\n")

UA = "Mozilla/5.0 (compatible; RQTalentBot/1.0; +https://rydequest-max.github.io/rq-talent/)"

# ── Region detection ──────────────────────────────────────────────────────────
COUNTRY_PATTERNS = {
    "United Arab Emirates": [
        "united arab emirates", "uae", "u.a.e", "dubai", "abu dhabi", "sharjah",
        "ajman", "ruwais", "fujairah", "al ain", "jebel ali",
    ],
    "Qatar": ["qatar", "doha", "ras laffan", "mesaieed", "dukhan", "lusail"],
    "Saudi Arabia": [
        "saudi arabia", "ksa", "k.s.a", "riyadh", "jeddah", "dammam", "khobar",
        "al khobar", "jubail", "yanbu", "ras tanura", "dhahran", "jizan",
        "tabuk", "neom", "mecca", "medina",
    ],
}

# City search terms per country (for Workday queries that list city-only locations)
CITY_QUERY = {
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
    "Qatar": ["Doha"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Dammam", "Dhahran"],
}

# ── Shutdown / turnaround detection ─────────────────────────────────────────────
SHUTDOWN_TERMS = [
    "shutdown", "shut down", "shut-down", "turnaround", "turn around",
    "turn-around", " tar ", "t&i", "t & i", " sto ", "plant shutdown",
    "major maintenance", "planned maintenance", "outage", "commissioning",
    "pre-commissioning", "precommissioning", "tie-in", "tie in", "hook-up",
    "hook up", "hookup", "mechanical completion", "start-up", "startup support",
]

# ── Skill vocabulary (extends the portal's matcher; energy-weighted) ─────────────
SKILL_VOCAB = [
    # process / mechanical / static / rotating
    "process engineering", "piping", "pipeline", "rotating equipment",
    "static equipment", "pressure vessels", "heat exchangers", "compressors",
    "pumps", "turbines", "valves", "flange management",
    # inspection / integrity
    "ndt", "rope access", "api 510", "api 570", "api 653", "cswip", "bgas",
    "welding inspection", "qa/qc", "quality control", "asset integrity",
    "corrosion", "cathodic protection",
    # disciplines
    "instrumentation", "electrical", "civil", "structural", "hvac",
    "telecommunications", "scada", "dcs", "plc", "control systems",
    # planning / project
    "primavera", "p6", "planner", "scheduler", "cost control", "estimation",
    "project management", "contracts", "procurement", "expediting",
    # field / construction
    "rigging", "scaffolding", "welding", "fabrication", "construction",
    "field engineering", "commissioning", "pre-commissioning",
    # safety
    "hse", "nebosh", "iosh", "permit to work", "ptw", "safety officer",
    "h2s", "confined space",
    # domain
    "oil and gas", "petrochemical", "refinery", "lng", "gas processing",
    "upstream", "downstream", "offshore", "onshore", "subsea", "drilling",
    "epc", "fpso",
    # general tech (kept for cross-industry candidates)
    "python", "sql", "aws", "azure", "kubernetes", "terraform", "react",
    "java", "autocad", "sap", "maximo",
]

# ── Industry classification (maps to the portal's INDUSTRIES names) ─────────────
INDUSTRY_KEYWORDS = {
    "Hospitality / Tourism": ["hotel", "hospitality", "resort", "restaurant", "chef",
        "f&b", "food and beverage", "guest", "housekeeping", "concierge", "culinary",
        "front office", "tourism", "banquet", "barista", "waiter", "waitress", "spa",
        "reservations", "butler", "sommelier", "catering"],
    "Construction / Infrastructure": ["construction", "civil engineer", "structural",
        "quantity surveyor", "site engineer", "mep", "hvac", "building", "infrastructure",
        "rail", "roads", "bridge", "bim", "draughtsman", "draftsman", "surveyor",
        "site supervisor", "scaffolding", "formwork", "architect", "facade", "estimator"],
    "Financial Services / Fintech": ["bank", "banking", "finance", "financial", "investment",
        "trading", "credit", "underwriting", "treasury", "wealth", "fintech", "payments",
        "actuarial", "relationship manager", "portfolio", "kyc", "aml", "accountant",
        "accounting", "audit", "tax", "fund", "equities", "asset management"],
    "Healthcare / Pharma": ["nurse", "nursing", "physician", "doctor", "clinical", "medical",
        "healthcare", "patient", "pharmacy", "pharma", "radiolog", "surgeon", "therapist",
        "laboratory", "dental", "midwife", "physiotherap", "anaesth", "anesth", "paramedic",
        "phlebotom", "sonographer", "registrar", "consultant cardiolog"],
    "Technology / Software": ["software", "developer", "data engineer", "data scientist",
        "cloud", "devops", "cybersecurity", "full stack", "frontend", "front-end", "backend",
        "back-end", "machine learning", " ai ", "sre", "product manager", "ux", "ui/ux",
        "kubernetes", "python", "java developer", ".net", "react", "qa engineer",
        "it support", "system administrator", "network engineer", "salesforce", "sap"],
    "Energy / Oil & Gas": ["oil", " gas ", "petroleum", "refinery", "lng", "drilling",
        "upstream", "downstream", "petrochemical", "turnaround", "shutdown", "pipeline",
        "offshore", "subsea", "rotating equipment", "static equipment", "hse", "wellsite",
        "reservoir", "solar", "renewable", "turbine", "power plant", "utilities"],
}


def classify_industry(title, desc, company):
    blob = (" " + (title or "") + " " + (desc or "") + " " + (company or "") + " ").lower()
    best, best_n = "Other", 0
    for ind, kws in INDUSTRY_KEYWORDS.items():
        n = sum(1 for k in kws if k in blob)
        if n > best_n:
            best_n, best = n, ind
    return best if best_n > 0 else "Other"


EMAIL_RE = re.compile(r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}")
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")

SENIORITY_MAP = [
    ("Lead", ["lead", "principal", "head of", "director", "vp", "chief", "manager"]),
    ("Senior", ["senior", "sr.", "sr ", "specialist", "supervisor", "superintendent"]),
    ("Junior", ["junior", "jr.", "graduate", "trainee", "intern", "entry"]),
]


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def http_get(url, timeout, headers=None):
    h = {"User-Agent": UA, "Accept": "application/json, text/xml, */*"}
    if headers:
        h.update(headers)
    req = urllib.request.Request(url, headers=h)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8", "replace")


def http_post_json(url, payload, timeout):
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url, data=data,
        headers={"User-Agent": UA, "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8", "replace")


def clean_text(html):
    if not html:
        return ""
    txt = TAG_RE.sub(" ", html)
    txt = (txt.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
              .replace("&nbsp;", " ").replace("&quot;", '"').replace("&#39;", "'"))
    return WS_RE.sub(" ", txt).strip()


def detect_country(*texts):
    blob = " ".join(t for t in texts if t).lower()
    for country, pats in COUNTRY_PATTERNS.items():
        for p in pats:
            if p in blob:
                return country
    return None


def detect_city(country, *texts):
    blob = " ".join(t for t in texts if t).lower()
    if not country:
        return ""
    for p in COUNTRY_PATTERNS[country]:
        # skip the country-name aliases, keep the city-looking ones
        if p in blob and p not in (country.lower(), "uae", "u.a.e", "ksa", "k.s.a"):
            return p.title()
    return ""


def is_shutdown(title, desc):
    blob = (" " + (title or "") + " " + (desc or "") + " ").lower()
    return any(term in blob for term in SHUTDOWN_TERMS)


def extract_skills(title, desc):
    blob = (" " + (title or "") + " " + (desc or "") + " ").lower()
    found = []
    for skill in SKILL_VOCAB:
        if skill in blob:
            found.append(skill)
    # de-dupe while preserving order, cap to keep payload small
    seen, out = set(), []
    for s in found:
        if s not in seen:
            seen.add(s); out.append(s)
    return out[:25]


def detect_seniority(title):
    t = (title or "").lower()
    for label, cues in SENIORITY_MAP:
        if any(c in t for c in cues):
            return label
    return "Mid"


def find_contact(desc):
    if not desc:
        return None
    m = EMAIL_RE.search(desc)
    if not m:
        return None
    email = m.group(0)
    # skip obvious noise
    if any(x in email.lower() for x in ("example.com", "sentry", "wixpress", "no-reply", "noreply")):
        return None
    return email


def make_id(source, url, title, company):
    basis = (url or "") + "|" + (title or "") + "|" + (company or "")
    return source.split(":")[0].lower() + "_" + hashlib.sha1(basis.encode("utf-8")).hexdigest()[:14]


def normalize(*, source, title, company, location, description, url,
              salary=None, posted=None, company_type="unknown", industry=None, cfg=None):
    title = clean_text(title)
    company = clean_text(company) or "—"
    location = clean_text(location)
    desc = clean_text(description)
    maxc = (cfg or {}).get("max_description_chars", 4000)
    if len(desc) > maxc:
        desc = desc[:maxc] + " …"
    country = detect_country(location, title, desc)
    return {
        "id": make_id(source, url, title, company),
        "title": title,
        "company": company,
        "location": location or (country or ""),
        "country": country,
        "city": detect_city(country, location),
        "description": desc,
        "url": url or "",
        "source": source,
        "company_type": company_type,
        "industry": industry or classify_industry(title, desc, company),
        "salary": salary,
        "contact": find_contact(desc),
        "skills": extract_skills(title, desc),
        "seniority": detect_seniority(title),
        "shutdown": is_shutdown(title, desc),
        "posted": posted,
    }


# ════════════════════════════════════════════════════════════════════════════
#  SOURCE ADAPTERS  — each returns a list of normalized jobs, never raises.
# ════════════════════════════════════════════════════════════════════════════

def adapter_jooble(cfg):
    key = os.environ.get("JOOBLE_API_KEY", "").strip()
    if not (cfg.get("jooble_enabled") and key):
        return [], "Jooble (skipped: no JOOBLE_API_KEY)"
    out = []
    timeout = cfg.get("request_timeout", 20)
    locations = cfg.get("target_countries", []) or ["United Arab Emirates"]
    # One keyword string for the API. Prefer an explicit broad query (incl. HR) if set.
    keywords = cfg.get("jooble_query") or " OR ".join(cfg["keywords"][:8])
    pages = max(1, int(cfg.get("jooble_pages", 1)))   # each page = 1 API request
    # (query, pages) list. A dedicated narrow query (e.g. HR) guarantees those roles
    # surface instead of being crowded out of the broad query's first pages.
    queries = [(keywords, pages)]
    if cfg.get("jooble_hr_query"):
        queries.append((cfg["jooble_hr_query"], max(1, int(cfg.get("jooble_hr_pages", 1)))))
    for loc in locations:
      for qstr, qpages in queries:
        for page in range(1, qpages + 1):
          try:
            body = http_post_json(
                f"https://jooble.org/api/{key}",
                {"keywords": qstr, "location": loc, "page": str(page)},
                timeout,
            )
            data = json.loads(body)
            jobs = data.get("jobs", [])
            if not jobs:
                break  # no more results — stop paging this location
            for j in jobs:
                out.append(normalize(
                    source="Jooble",
                    title=j.get("title"), company=j.get("company"),
                    location=j.get("location") or loc,
                    description=j.get("snippet"), url=j.get("link"),
                    salary=j.get("salary") or None, posted=j.get("updated"),
                    cfg=cfg,
                ))
            time.sleep(1)
          except Exception as e:
            print(f"  jooble[{loc}] error: {type(e).__name__}: {e}", file=sys.stderr)
    return out, f"Jooble ({len(out)})"


def adapter_careerjet(cfg):
    """Careerjet v4 API (search.api.careerjet.net/v4/query). Auth = HTTP Basic with
    the API key as username and an empty password. NOTE: Careerjet requires you to
    pre-declare the server IP(s) calls come from — so this only works from a fixed
    IP (a static-IP host or proxy), NOT from GitHub Actions' ephemeral runners."""
    import base64
    key = os.environ.get("CAREERJET_API_KEY", "").strip() or os.environ.get("CAREERJET_AFFID", "").strip()
    if not (cfg.get("careerjet_enabled") and key):
        return [], "Careerjet (skipped: no CAREERJET_API_KEY)"
    out = []
    timeout = cfg.get("request_timeout", 20)
    referer = cfg.get("careerjet_referer", "https://www.rydequest.com/find-jobs/")
    max_jobs = cfg.get("careerjet_max", 100)
    auth = "Basic " + base64.b64encode((key + ":").encode()).decode()
    locale_map = {"United Arab Emirates": "en_AE", "Qatar": "en_QA", "Saudi Arabia": "en_SA"}
    targets = cfg.get("target_countries", []) or ["United Arab Emirates"]

    # Careerjet authenticates by the CALLER's IP. On GitHub Actions the runner IP is
    # ephemeral, so route through a static-IP proxy (CAREERJET_PROXY) whose IP you
    # declare in the Careerjet dashboard. e.g. http://user:pass@proxy-host:port
    proxy = os.environ.get("CAREERJET_PROXY", "").strip()
    opener = urllib.request.build_opener(
        urllib.request.ProxyHandler({"http": proxy, "https": proxy}) if proxy
        else urllib.request.ProxyHandler({}))

    def cj_get(url):
        req = urllib.request.Request(url, headers={
            "User-Agent": UA, "Authorization": auth, "Referer": referer,
            "Content-Type": "application/json"})
        with opener.open(req, timeout=timeout) as r:
            return r.read().decode("utf-8", "replace")

    for loc in targets:
        locale = locale_map.get(loc, "en_GB")
        found = 0
        for page in range(1, 6):
            if found >= max_jobs:
                break
            try:
                params = urllib.parse.urlencode({
                    "locale_code": locale, "keywords": "", "location": loc,
                    "user_ip": "11.22.33.44", "user_agent": UA,
                    "page": str(page), "page_size": "100", "sort": "date",
                })
                body = cj_get(f"https://search.api.careerjet.net/v4/query?{params}")
                data = json.loads(body)
                if data.get("type") != "JOBS":
                    break
                jobs = data.get("jobs", [])
                if not jobs:
                    break
                for j in jobs:
                    out.append(normalize(
                        source="Careerjet",
                        title=j.get("title"), company=j.get("company"),
                        location=j.get("locations") or loc,
                        description=j.get("description"), url=j.get("url"),
                        salary=j.get("salary") or None, posted=j.get("date"),
                        cfg=cfg,
                    ))
                    found += 1
                time.sleep(1)
            except Exception as e:
                print(f"  careerjet[{loc} p{page}] error: {type(e).__name__}: {e}", file=sys.stderr)
                break
    return out, f"Careerjet ({len(out)})"


def adapter_greenhouse(cfg):
    out, timeout = [], cfg.get("request_timeout", 20)
    for entry in cfg.get("greenhouse_boards", []):
        token = entry if isinstance(entry, str) else entry.get("token")
        display = token.replace("-", " ").title() if isinstance(entry, str) else (entry.get("company") or token)
        ind = None if isinstance(entry, str) else entry.get("industry")
        try:
            body = http_get(
                f"https://boards-api.greenhouse.io/v1/boards/{token}/jobs?content=true",
                timeout,
            )
            data = json.loads(body)
            for j in data.get("jobs", []):
                loc = (j.get("location") or {}).get("name", "")
                if not detect_country(loc, j.get("title", "")):
                    continue  # target region only
                out.append(normalize(
                    source=f"Greenhouse:{display}",
                    title=j.get("title"), company=display,
                    location=loc, description=j.get("content"),
                    url=j.get("absolute_url"),
                    posted=j.get("updated_at"), company_type="employer",
                    industry=ind, cfg=cfg,
                ))
            time.sleep(0.5)
        except urllib.error.HTTPError as e:
            print(f"  greenhouse[{token}] HTTP {e.code} (token may not exist)", file=sys.stderr)
        except Exception as e:
            print(f"  greenhouse[{token}] error: {type(e).__name__}: {e}", file=sys.stderr)
    return out, f"Greenhouse ({len(out)})"


def adapter_lever(cfg):
    out, timeout = [], cfg.get("request_timeout", 20)
    for entry in cfg.get("lever_boards", []):
        token = entry if isinstance(entry, str) else entry.get("token")
        display = token.replace("-", " ").title() if isinstance(entry, str) else (entry.get("company") or token)
        ind = None if isinstance(entry, str) else entry.get("industry")
        try:
            body = http_get(f"https://api.lever.co/v0/postings/{token}?mode=json", timeout)
            data = json.loads(body)
            for j in data:
                loc = (j.get("categories") or {}).get("location", "")
                if not detect_country(loc, j.get("text", "")):
                    continue
                out.append(normalize(
                    source=f"Lever:{display}",
                    title=j.get("text"), company=display,
                    location=loc,
                    description=j.get("descriptionPlain") or j.get("description"),
                    url=j.get("hostedUrl"),
                    posted=datetime.fromtimestamp(
                        j.get("createdAt", 0) / 1000, timezone.utc).isoformat()
                        if j.get("createdAt") else None,
                    company_type="employer", industry=ind, cfg=cfg,
                ))
            time.sleep(0.5)
        except Exception as e:
            print(f"  lever[{token}] error: {type(e).__name__}: {e}", file=sys.stderr)
    return out, f"Lever ({len(out)})"


def adapter_rss(cfg):
    import xml.etree.ElementTree as ET
    out, timeout = [], cfg.get("request_timeout", 20)
    for url in cfg.get("rss_feeds", []):
        try:
            body = http_get(url, timeout)
            root = ET.fromstring(body)
            for item in root.iter("item"):
                def g(tag):
                    el = item.find(tag)
                    return el.text if el is not None else ""
                title = g("title")
                if not detect_country(title, g("description")):
                    continue
                out.append(normalize(
                    source="RSS",
                    title=title, company="", location="",
                    description=g("description"), url=g("link"),
                    posted=g("pubDate"), cfg=cfg,
                ))
        except Exception as e:
            print(f"  rss[{url}] error: {type(e).__name__}: {e}", file=sys.stderr)
    return out, f"RSS ({len(out)})"


def adapter_workday(cfg):
    """Workday's job API is open (no key). Big oilfield-services / energy firms use
    it. Each board = {host, tenant, site, company, type}. We page the listing,
    keep Gulf locations, then fetch each job's detail for the full JD."""
    out, timeout = [], cfg.get("request_timeout", 20)
    max_pages = cfg.get("workday_max_pages", 15)
    max_gulf = cfg.get("workday_max_per_board", 40)
    for b in cfg.get("workday_boards", []):
        host, ten, site = b.get("host"), b.get("tenant"), b.get("site")
        company = b.get("company") or ten
        ctype = b.get("type", "service")
        if not (host and ten and site):
            continue
        list_url = f"https://{host}/wday/cxs/{ten}/{site}/jobs"
        seen_paths, found = set(), 0
        # Query by target-country name AND its major cities (server-side narrows to
        # that region) — far fewer requests than paging the whole board, and catches
        # employers that list the city only (e.g. "Cleveland Clinic Abu Dhabi").
        queries = []
        for c in (cfg.get("target_countries", []) or ["United Arab Emirates"]):
            queries.append(c)
            queries.extend(CITY_QUERY.get(c, []))

        def fetch_page(off, q):
            body = json.dumps({"appliedFacets": {}, "limit": 20,
                               "offset": off, "searchText": q}).encode("utf-8")
            req = urllib.request.Request(
                list_url, data=body,
                headers={"User-Agent": UA, "Content-Type": "application/json",
                         "Accept": "application/json"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return json.loads(r.read().decode("utf-8", "replace"))

        try:
            for q in queries:
                if found >= max_gulf:
                    break
                first = fetch_page(0, q)
                total = first.get("total", 0)
                for off in range(0, min(total, max_pages * 20), 20):
                    page = first if off == 0 else fetch_page(off, q)
                    posts = page.get("jobPostings", [])
                    if not posts:
                        break
                    for p in posts:
                        loc = p.get("locationsText", "")
                        if not detect_country(loc):
                            continue
                        ext = p.get("externalPath", "")
                        if ext in seen_paths:
                            continue
                        seen_paths.add(ext)
                        apply_url = f"https://{host}/en-US/{site}{ext}"
                        desc, posted = "", None
                        try:
                            durl = f"https://{host}/wday/cxs/{ten}/{site}{ext}"
                            info = json.loads(http_get(durl, timeout)).get("jobPostingInfo", {})
                            desc = info.get("jobDescription", "") or ""
                            posted = info.get("startDate")
                            loc = info.get("location", loc) or loc
                        except Exception:
                            pass
                        out.append(normalize(
                            source=f"Workday:{company}", title=p.get("title"),
                            company=company, location=loc, description=desc,
                            url=apply_url, posted=posted, company_type=ctype,
                            industry=b.get("industry"), cfg=cfg))
                        found += 1
                        if found >= max_gulf:
                            break
                        time.sleep(0.12)
                    if found >= max_gulf:
                        break
                    time.sleep(0.1)
        except Exception as e:
            print(f"  workday[{company}] error: {type(e).__name__}: {e}", file=sys.stderr)
    return out, f"Workday ({len(out)})"


def adapter_smartrecruiters(cfg):
    """SmartRecruiters postings API is open (no key). AECOM and others use it.
    Each board = {company, display, industry}. Filtered server-side to country=ae
    (or cfg target). We page the listing, then fetch each posting's full JD."""
    out, timeout = [], cfg.get("request_timeout", 20)
    cap = cfg.get("smartrecruiters_max_per_board", 50)
    # country codes for SR's ?country= param
    cc = {"United Arab Emirates": "ae", "Qatar": "qa", "Saudi Arabia": "sa"}
    countries = [cc[c] for c in cfg.get("target_countries", []) if c in cc] or ["ae"]
    for b in cfg.get("smartrecruiters_boards", []):
        cid = b.get("company")
        if not cid:
            continue
        disp = b.get("display") or cid
        found = 0
        for country in countries:
            if found >= cap:
                break
            try:
                offset = 0
                while found < cap:
                    lurl = (f"https://api.smartrecruiters.com/v1/companies/{cid}/postings"
                            f"?limit=100&offset={offset}&country={country}")
                    data = json.loads(http_get(lurl, timeout))
                    items = data.get("content", [])
                    if not items:
                        break
                    for it in items:
                        loc = (it.get("location") or {}).get("fullLocation") \
                            or ", ".join(filter(None, [(it.get("location") or {}).get("city"),
                                                       (it.get("location") or {}).get("region")]))
                        pid = it.get("id")
                        desc, apply_url = "", f"https://jobs.smartrecruiters.com/{cid}/{pid}"
                        try:
                            det = json.loads(http_get(
                                f"https://api.smartrecruiters.com/v1/companies/{cid}/postings/{pid}", timeout))
                            secs = det.get("jobAd", {}).get("sections", {})
                            desc = " ".join(filter(None, [
                                secs.get("jobDescription", {}).get("text", ""),
                                secs.get("qualifications", {}).get("text", "")]))
                            apply_url = det.get("postingUrl") or det.get("applyUrl") or apply_url
                        except Exception:
                            pass
                        out.append(normalize(
                            source=f"SmartRecruiters:{disp}", title=it.get("name"),
                            company=disp, location=loc, description=desc, url=apply_url,
                            posted=it.get("releasedDate"), company_type="employer",
                            industry=b.get("industry"), cfg=cfg))
                        found += 1
                        if found >= cap:
                            break
                        time.sleep(0.15)
                    if len(items) < 100:
                        break
                    offset += 100
            except Exception as e:
                print(f"  smartrecruiters[{disp}/{country}] error: {type(e).__name__}: {e}", file=sys.stderr)
    return out, f"SmartRecruiters ({len(out)})"


ADAPTERS = [adapter_jooble, adapter_careerjet, adapter_workday,
            adapter_smartrecruiters, adapter_greenhouse, adapter_lever, adapter_rss]


# ════════════════════════════════════════════════════════════════════════════
#  MERGE + WRITE
# ════════════════════════════════════════════════════════════════════════════

def load_existing():
    try:
        with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        return {j["id"]: j for j in data.get("jobs", [])}
    except Exception:
        return {}


def main():
    cfg = load_config()
    target = set(cfg.get("target_countries", []))
    print(f"RQ Talent scraper — {now_iso()}")

    scraped, summaries = [], []
    for adapter in ADAPTERS:
        try:
            jobs, summary = adapter(cfg)
        except Exception as e:
            jobs, summary = [], f"{adapter.__name__} crashed: {e}"
        scraped.extend(jobs)
        summaries.append(summary)
        print("  •", summary)

    # keep only target-country jobs with a usable title
    fresh = [j for j in scraped if j["title"] and (j["country"] in target)]

    existing = load_existing()
    now = now_iso()
    seen_now = set()
    for j in fresh:
        seen_now.add(j["id"])
        if j["id"] in existing:
            prev = existing[j["id"]]
            j["first_seen"] = prev.get("first_seen", now)
        else:
            j["first_seen"] = now
        j["last_seen"] = now
        existing[j["id"]] = j

    # carry forward jobs not seen this run, drop stale ones
    retention = timedelta(days=cfg.get("retention_days", 21))
    cutoff = datetime.now(timezone.utc) - retention
    merged = []
    for jid, j in existing.items():
        if jid not in seen_now:
            try:
                if datetime.fromisoformat(j.get("last_seen", now)) < cutoff:
                    continue  # stale -> drop
            except Exception:
                pass
        merged.append(j)

    # newest first by first_seen
    merged.sort(key=lambda x: x.get("first_seen", ""), reverse=True)

    industries = {}
    for j in merged:
        industries[j.get("industry", "Other")] = industries.get(j.get("industry", "Other"), 0) + 1
    payload = {
        "generated_at": now,
        "count": len(merged),
        "shutdown_count": sum(1 for j in merged if j.get("shutdown")),
        "by_country": {c: sum(1 for j in merged if j.get("country") == c) for c in target},
        "by_industry": dict(sorted(industries.items(), key=lambda kv: -kv[1])),
        "sources": summaries,
        "jobs": merged,
    }
    write_outputs(payload)
    print(f"Wrote {OUTPUT_PATH} (+ jobs.js): {len(merged)} jobs "
          f"({payload['shutdown_count']} shutdown). New this run: {len(seen_now)}.")


if __name__ == "__main__":
    main()
